filebeat.inputs:
- type: log
  paths:
    - /var/ossec/logs/alerts/alerts.json
  multiline:
    pattern: '^{'
    negate: true
    match: after

output.elasticsearch:
  hosts: ["https://wazuh1-indexer:9200", "https://wazuh2-indexer:9200", "https://wazuh3-indexer:9200"]
  username: "logstash"
  password: "logstash"
  ssl:
    certificate_authorities: ["/etc/ssl/root-ca.pem"]
    certificate: "/etc/ssl/filebeat.pem"
    key: "/etc/ssl/filebeat-key.pem"

setup.ilm.enabled: false
setup.template.enabled: false
