filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.overwrite: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["https://wazuh1-indexer:9200", "https://wazuh2-indexer:9200", "https://wazuh3-indexer:9200"]
  username: "logstash"
  password: "logstash"
  protocol: "https"
  ssl:
    verification_mode: full
    certificate_authorities: ["/etc/ssl/root-ca.pem"]
    certificate: "/etc/ssl/wazuh-master.pem"
    key: "/etc/ssl/wazuh-master-key.pem"
  indices:
    - index: "wazuh-alerts-4.x-%{+yyyy.MM.dd}"
  setup.template.settings:
    index.mapping.single_type: false

logging.level: debug
logging.to_files: true
logging.files:
  path: /var/ossec/logs/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0640

seccomp:
  default_action: allow
  syscalls:
    - action: allow
      names:
        - rseq
