name: Wazuh CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Create and activate virtual environment
        run: |
          python3 -m venv wazuh-venv
          source wazuh-venv/bin/activate
          pip install hvac pytest selenium requests docker
          deactivate

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.65.0/trivy_0.65.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.65.0_Linux-64bit.deb

      - name: Scan Docker images with Trivy
        run: |
          trivy image --config trivy.yaml --severity CRITICAL,HIGH --exit-code 1 wazuh/wazuh-manager:4.12.0
          trivy image --config trivy.yaml --severity CRITICAL,HIGH --exit-code 1 wazuh/wazuh-indexer:4.12.0
          trivy image --config trivy.yaml --severity CRITICAL,HIGH --exit-code 1 wazuh/wazuh-dashboard:4.12.0
          trivy image --config trivy.yaml --severity CRITICAL,HIGH --exit-code 1 nginx:stable

      - name: Run Selenium tests
        run: |
          source wazuh-venv/bin/activate
          export DASHBOARD_USERNAME=kibanaserver
          export DASHBOARD_PASSWORD=kibanaserver
          python3 -m pytest tests/selenium/test_dashboard.py
          deactivate

      - name: Run API tests
        run: |
          source wazuh-venv/bin/activate
          export API_USERNAME=wazuh-wui
          export API_PASSWORD=MyS3cr37P450r.*-
          python3 -m pytest tests/api/health_check.py
          deactivate

      - name: Deploy Wazuh stack
        run: |
          source wazuh-venv/bin/activate
          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}
          ansible-playbook -i ansible/inventory.yml ansible/deploy-wazuh.yml --vault-password-file vault-pass.txt
          deactivate
